pipeline {
    agent any

    tools {
        nodejs 'node20'
    }

    environment {
        HEROKU_APP_NAME = 'pipeline_as_code'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Install & Build') {
            steps {
                sh 'npm install'
                sh 'npm run build'
            }
        }
        stage('Deploy') {
            steps {
                withCredentials([string(credentialsId: 'HEROKU_API_KEY', variable: 'HEROKU_TOKEN')]) {
                    sh "git remote add heroku https://root:${HEROKU_TOKEN}@git.heroku.com/${HEROKU_APP_NAME}.git || true"
                    sh "git push heroku main:master --force"
                }
            }
        }
    }
}
